"""csm-account-pulse — single-page Monday morning dashboard.

What a CSM sees: their accounts ranked by risk, with a 3-bullet briefing per account
that cites the underlying signals. The briefing is generated by an LLM (or a deterministic
stub if no API key is set) — both paths produce the same Pydantic-validated structure.

Run:
    streamlit run app.py
"""

from __future__ import annotations

import os
from datetime import date, timedelta

import streamlit as st
from dotenv import load_dotenv

from briefing import generate_briefing
from datasource import FixtureDataSource
from health import compute_health
from models import AccountState, HealthBucket


load_dotenv()

TODAY = date(2026, 4, 26)
USAGE_LOOKBACK_DAYS = 30
FIXTURES_VERSION = "v1"  # bump to bust @st.cache_data after fixture regeneration

BUCKET_ORDER = {
    HealthBucket.CRITICAL: 0,
    HealthBucket.AT_RISK: 1,
    HealthBucket.WATCH: 2,
    HealthBucket.HEALTHY: 3,
}
BUCKET_COLOR = {
    HealthBucket.CRITICAL: "#c0392b",
    HealthBucket.AT_RISK: "#e67e22",
    HealthBucket.WATCH: "#f1c40f",
    HealthBucket.HEALTHY: "#27ae60",
}


@st.cache_data(show_spinner=False)
def load_scored_accounts(_cache_version: str = FIXTURES_VERSION) -> list[AccountState]:
    """Returns AccountStates sorted worst-health first. _cache_version arg lets us
    invalidate when fixtures change (Streamlit caches on input hash, not file content)."""
    ds = FixtureDataSource()
    states: list[AccountState] = []
    since = TODAY - timedelta(days=USAGE_LOOKBACK_DAYS)
    for a in ds.list_accounts():
        events = ds.get_usage_events(a.id, since=since)
        all_events_for_score = ds.get_usage_events(a.id)
        tickets = ds.get_tickets(a.id)
        nps = ds.get_nps_responses(a.id)
        health = compute_health(a, all_events_for_score, tickets, nps, TODAY)
        states.append(AccountState(
            account=a,
            health=health,
            recent_usage_events=events,
            tickets=tickets,
            nps_responses=nps,
        ))
    states.sort(key=lambda s: (BUCKET_ORDER[s.health.bucket], s.health.score, -s.account.arr_usd))
    return states


@st.cache_data(show_spinner="Generating briefing...")
def cached_briefing(
    account_id: str,
    _llm_mode: str,
    _cache_version: str = FIXTURES_VERSION,
) -> dict:
    """Briefing keyed by (account_id, llm_mode). _llm_mode partitions the cache so
    that flipping ANTHROPIC_API_KEY between blank and set across reruns doesn't
    serve stub output under an Anthropic badge (or vice versa). _cache_version
    handles fixture-file changes — Streamlit caches on input hash, not file content."""
    states = load_scored_accounts(_cache_version)
    state = next(s for s in states if s.account.id == account_id)
    api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip() or None
    briefing = generate_briefing(state, api_key=api_key)
    return briefing.model_dump(mode="json")


def _bucket_pill(bucket: HealthBucket) -> str:
    color = BUCKET_COLOR[bucket]
    return (
        f"<span style='background:{color};color:white;padding:2px 8px;"
        f"border-radius:10px;font-size:0.8em;font-weight:600;'>{bucket.value}</span>"
    )


def render_account_row(state: AccountState) -> None:
    a = state.account
    h = state.health
    days_to_renewal = (a.renewal_date - TODAY).days

    with st.container(border=True):
        c1, c2 = st.columns([3, 1])
        with c1:
            st.markdown(
                f"### {a.name} &nbsp; {_bucket_pill(h.bucket)}",
                unsafe_allow_html=True,
            )
            st.caption(
                f"{a.id} · {a.plan_tier} · ${a.arr_usd:,} ARR · "
                f"{a.industry} · {a.employee_count:,} employees · "
                f"renewal in {days_to_renewal}d ({a.renewal_date.isoformat()}) · "
                f"CSM: {a.csm_owner}"
            )
        with c2:
            st.metric("Health score", h.score)

        st.markdown(f"**Why:** {h.rationale}")

        sig_cols = st.columns(4)
        sig_cols[0].metric(
            "Usage WoW",
            f"{h.signals.usage_decay_pct:.0f}%",
            delta=None,
            help="Positive = decay (last 7 days vs prior 7 days).",
        )
        sig_cols[1].metric(
            "Open H/C tickets",
            h.signals.open_high_severity_tickets,
            help="High + critical severity tickets currently open or pending.",
        )
        sig_cols[2].metric(
            "Tickets (30d)",
            h.signals.ticket_volume_30d,
        )
        sig_cols[3].metric(
            "Latest NPS",
            h.signals.latest_nps_score if h.signals.latest_nps_score is not None else "—",
            help=f"{h.signals.detractor_count_90d} detractor(s) in last 90 days.",
        )

        with st.expander("This week's briefing", expanded=h.bucket in (HealthBucket.CRITICAL, HealthBucket.AT_RISK)):
            llm_mode = "anthropic" if os.environ.get("ANTHROPIC_API_KEY", "").strip() else "stub"
            briefing = cached_briefing(a.id, _llm_mode=llm_mode)
            badge = "Anthropic" if briefing["generated_by"] == "anthropic" else "Stub (no API key)"
            st.markdown(f"**{briefing['headline']}** &nbsp; *<sub>{badge}</sub>*", unsafe_allow_html=True)
            for bullet in briefing["bullets"]:
                st.markdown(f"- {bullet['text']}")
                cite_str = " · ".join(f"`{c}`" for c in bullet["citations"])
                st.caption(f"&nbsp;&nbsp;&nbsp;&nbsp;cites: {cite_str}", unsafe_allow_html=True)


def render_sidebar(states: list[AccountState]) -> tuple[set[HealthBucket], str | None]:
    st.sidebar.title("Filters")
    st.sidebar.caption("Showing the Monday morning view as of " + TODAY.isoformat())

    bucket_choices = st.sidebar.multiselect(
        "Health bucket",
        options=[b.value for b in HealthBucket],
        default=[HealthBucket.CRITICAL.value, HealthBucket.AT_RISK.value, HealthBucket.WATCH.value],
    )
    selected_buckets = {HealthBucket(v) for v in bucket_choices}

    csms = sorted({s.account.csm_owner for s in states})
    csm_filter = st.sidebar.selectbox("CSM", options=["All"] + csms, index=0)
    csm_filter = None if csm_filter == "All" else csm_filter

    st.sidebar.divider()
    api_set = bool(os.environ.get("ANTHROPIC_API_KEY", "").strip())
    st.sidebar.markdown("**LLM source:** " + ("Anthropic API" if api_set else "Deterministic stub"))
    st.sidebar.caption(
        "Set `ANTHROPIC_API_KEY` in `.env` to use the live model. "
        "The dashboard runs end-to-end either way."
    )
    if st.sidebar.button("Clear briefing cache"):
        cached_briefing.clear()
        st.rerun()

    return selected_buckets, csm_filter


def main() -> None:
    st.set_page_config(
        page_title="CSM Account Pulse",
        page_icon="📈",
        layout="wide",
    )

    st.title("CSM Account Pulse")
    st.caption(
        "What needs your attention this week. Aggregates usage, support, and NPS per account, "
        "computes a health score, and asks an LLM to summarize the week ahead in 3 cited bullets."
    )

    states = load_scored_accounts()
    selected_buckets, csm_filter = render_sidebar(states)

    filtered = [s for s in states if s.health.bucket in selected_buckets]
    if csm_filter:
        filtered = [s for s in filtered if s.account.csm_owner == csm_filter]

    summary_cols = st.columns(4)
    counts = {b: sum(1 for s in states if s.health.bucket == b) for b in HealthBucket}
    summary_cols[0].metric("Critical", counts[HealthBucket.CRITICAL])
    summary_cols[1].metric("At-Risk", counts[HealthBucket.AT_RISK])
    summary_cols[2].metric("Watch", counts[HealthBucket.WATCH])
    summary_cols[3].metric("Healthy", counts[HealthBucket.HEALTHY])

    st.divider()
    st.markdown(f"### {len(filtered)} account(s) match your filters")
    if not filtered:
        st.info("No accounts match. Loosen the filters in the sidebar.")
        return

    for state in filtered:
        render_account_row(state)


if __name__ == "__main__":
    main()
